# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Delta Gohugo Theme"
license = "MIT"
licenselink = "https://github.com/deltablot/hugo-theme-delta/blob/master/LICENSE.md"
description = "Hugo theme for Deltablot"
homepage = "https://github.com/deltablot/hugo-theme-delta"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons", "Multilingual", "Stackbit"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.54.0"

[author]
  name = "Nicolas CARPi"
  homepage = "https://github.com/NicolasCARPi"
